### ISSUE TITLE
There is a race condition while getting the PID list

### ISSUE THREAD

**Issue by hcloudclassic** [hcloud-classic/hcc-tuba#1]
There is a race condition in `dao/taskDao.go` getPIDList() function.
We are using go routine while getting the PID list.
We must add lock while appending the PID list.

@jollaman999

**Comment by jollaman999** [comment]
@hcloudclassic Thanks. I added a mutex lock to prevent races.
Fixed in https://github.com/hcloud-classic/hcc-tuba/commit/3eeeb0df1cfbe20cf61f44656e2977ad9e76600c.
